/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.Patient;

import hospital_Admission.*;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author wolf
 */
public class Addmission_Registration extends javax.swing.JFrame {

    /**
     * Creates new form HospitalRegistration
     */
    public Addmission_Registration() {
        initComponents();
        this.setResizable(false);
        this.setTitle("HospitalRegistration");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idcard = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        cellphone = new javax.swing.JTextField();
        department = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        doctor = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        sex = new javax.swing.JComboBox();
        year = new javax.swing.JComboBox();
        month = new javax.swing.JComboBox();
        day = new javax.swing.JComboBox();
        year1 = new javax.swing.JComboBox();
        month1 = new javax.swing.JComboBox();
        day1 = new javax.swing.JComboBox();
        search = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Hospital Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 370, 40));

        jLabel2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("IDCard:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Age:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("DateOfBirth:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("CellPhoneNumber:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Department:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("DateOfAdmmision:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Doctor:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));
        getContentPane().add(idcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 88, 285, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 128, 285, -1));
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 168, 86, -1));
        getContentPane().add(cellphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 246, 285, -1));

        department.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "orthopedics", "pediatric", "dermatology" }));
        getContentPane().add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 285, 119, -1));

        jLabel11.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Sex:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 170, -1, -1));

        doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorActionPerformed(evt);
            }
        });
        getContentPane().add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 364, 285, -1));

        submit.setFont(new java.awt.Font("宋体", 0, 20)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 419, -1, -1));

        cancel.setFont(new java.awt.Font("宋体", 0, 20)); // NOI18N
        cancel.setText("Back");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        sex.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 207, -1, -1));

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 207, -1, -1));

        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 207, -1, -1));

        year1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019" }));
        getContentPane().add(year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 325, -1, -1));

        month1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(month1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 325, -1, -1));

        day1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(day1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 325, -1, -1));

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 87, -1, -1));

        jLabel12.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel12.setText("Tips 1.You can enter a idcard to search if you have signed up");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/desk6.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try
        {
            Connection con=DBClass.getConnection(); 
            String str="insert into patient values(?,?,?,?,?,?,?,?,?)";  
            PreparedStatement pst=con.prepareStatement(str);
            pst.setString(1, idcard.getText());
            String nameP=name.getText();
            Pattern namePattern=Pattern.compile("^[a-zA-Z]+$");
            Matcher nameMatcher=namePattern.matcher(nameP);
            Boolean nameBoolean=nameMatcher.matches();
            if(nameBoolean==false)
                throw new Exception("Please enter the correct name(only character)");
            pst.setString(2, name.getText());
            if(Integer.parseInt(age.getText())<0||Integer.parseInt(age.getText())>100)
            {
                throw new Exception("Please enter the correct age");
            }
            pst.setInt(3, Integer.parseInt(age.getText()));
            pst.setString(4, sex.getSelectedItem().toString());
//            String dobP=dob.getText();
//            Pattern dobPattern=Pattern.compile("(//d{4}-)?(//d{2}-)?//d{2}");
//            Matcher dobMatcher=dobPattern.matcher(dobP);
//            Boolean dobBoolean=dobMatcher.matches();
//            if(dobBoolean==false)
//                throw new Exception("Please enter the correct date of birth(xxxx-xx-xx for example(2018-01-01))");
//            pst.setString(5, dob.getText());
            pst.setString(5, year.getSelectedItem().toString()+"-"+month.getSelectedItem().toString()+"-"+day.getSelectedItem().toString());
            pst.setString(6, cellphone.getText());
            pst.setString(7, department.getSelectedItem().toString());
//            String doaP=doa.getText();
//            Pattern doaPattern=Pattern.compile("(//d{4}-)?(//d{2}-)?//d{2}");
//            Matcher doaMatcher=doaPattern.matcher(doaP);
//            Boolean doaBoolean=doaMatcher.matches();
//            if(doaBoolean==false)
//                throw new Exception("Please enter the correct date of addmison(xxxx-xx-xx for example(2018-01-01))");
//            pst.setString(8, doa.getText());
            pst.setString(8, year1.getSelectedItem().toString()+"-"+month1.getSelectedItem().toString()+"-"+day1.getSelectedItem().toString());
            String doctorP=doctor.getText();
            Pattern doctorPattern=Pattern.compile("^[a-zA-Z]+$");
            Matcher doctorMatcher=doctorPattern.matcher(doctorP);
            Boolean doctorBoolean=doctorMatcher.matches();
            if(doctorBoolean==false)
                throw new Exception("Please enter the correct doctor name(only character)");
            pst.setString(9, doctor.getText());
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date dt1=df.parse(year1.getSelectedItem().toString()+"-"+month1.getSelectedItem().toString()+"-"+day1.getSelectedItem().toString());
            Date dt3=df.parse(year.getSelectedItem().toString()+"-"+month.getSelectedItem().toString()+"-"+day.getSelectedItem().toString());
            java.util.Date date=new java.util.Date();
            String datestr=new SimpleDateFormat("yyyy-MM-dd").format(date);
            Date dt2=df.parse(datestr);
            if(dt1.getTime()>dt2.getTime())
                throw new Exception("Your addmison date must be less than today");
            if(dt3.getTime()>dt2.getTime())
                throw new Exception("Your birthday must be less than today");
            if(dt3.getTime()>dt1.getTime())
                throw new Exception("Your addmison date must be more than your birthday");
            int rs=pst.executeUpdate();
            if(rs>0)
            {
                JOptionPane.showMessageDialog(this, "Insert successfully");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Not insert successfully");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       if(!idcard.getText().isEmpty())
       {   try
       {
           Connection con=DBClass.getConnection();
           PreparedStatement pst=con.prepareStatement("select present_name from present where present_id=?");
           pst.setString(1, idcard.getText());
           ResultSet rs=(ResultSet) pst.executeQuery();
           if(rs.next())
           {
               name.setText(rs.getString(1));
           }
           else
           {
               throw new Exception("Can't find");
           }
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this, e.getMessage());
       }}
    }//GEN-LAST:event_searchActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
        new Patient().show();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addmission_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addmission_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addmission_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addmission_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Addmission_Registration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cellphone;
    private javax.swing.JComboBox day;
    private javax.swing.JComboBox day1;
    private javax.swing.JComboBox department;
    private javax.swing.JTextField doctor;
    private javax.swing.JTextField idcard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox month;
    private javax.swing.JComboBox month1;
    private javax.swing.JTextField name;
    private javax.swing.JButton search;
    private javax.swing.JComboBox sex;
    private javax.swing.JButton submit;
    private javax.swing.JComboBox year;
    private javax.swing.JComboBox year1;
    // End of variables declaration//GEN-END:variables
}
