/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.Patient;

import com.mysql.jdbc.Statement;
import hospital.JDBC;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Registration extends javax.swing.JFrame {

    public Registration() {
        initComponents();
        setTitle("Registration");
        setLocationRelativeTo(null);
        try {
            Connection connection = JDBC.getConnection();
            String sql2 = "select * from present where idx=1";
            PreparedStatement ps2 = connection.prepareStatement(sql2);
            ResultSet rs;
            rs = ps2.executeQuery();
            while (rs.next()) {
                jTextField1.setText(rs.getString("present_id"));
                jTextField2.setText(rs.getString("present_name"));
            }
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
        } catch (Exception a) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        department = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        doctor = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("ID card：");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 72, -1, 40));

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Name：");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 122, -1, 40));

        jTextField1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 72, 258, 40));

        jTextField2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 122, 258, 40));

        jButton1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 120, -1));

        department.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Department", "The Orthopaedic", "Pediatric", "Dermatology", "Internal medicine", "Surgical", "Ophthalmology department" }));
        department.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                departmentItemStateChanged(evt);
            }
        });
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });
        getContentPane().add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 180, 260, 42));

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Department:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 187, -1, -1));

        jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Doctor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 248, -1, -1));

        doctor.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        doctor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Doctor" }));
        doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorActionPerformed(evt);
            }
        });
        getContentPane().add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 240, 260, 44));

        jButton2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jButton2.setText("<<  Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/hospital1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String item=(String) doctor.getItemAt(0);
        if("Choose Doctor".equals(item)){
            JOptionPane.showMessageDialog(null, "Please Chooese Doctor");
        }
        else{
            String sql1 = "insert into patient_info values(?,?,?,?,?,?,?,?,?,?)";
        try {
            Connection connection = JDBC.getConnection();
            String sql2 = "select * from present where idx=1";
            PreparedStatement ps2 = connection.prepareStatement(sql2);
            ResultSet rs;
            rs = ps2.executeQuery();
            while(rs.next()){
            PreparedStatement ps1 = connection.prepareStatement(sql1);
            ps1.setString(1, null);
            ps1.setString(2, null);
            ps1.setString(3, rs.getString("present_id"));
            ps1.setString(4, rs.getString("present_name"));
            ps1.setString(5, rs.getString("present_sex"));
            ps1.setString(6, null);
            ps1.setString(7, null);
            ps1.setString(8, null);
            ps1.setString(9, doctor.getSelectedItem().toString());
            ps1.setString(10, department.getSelectedItem().toString());
            ps1.executeUpdate();
            }
            String sql3 = "select max(reginum) from patient_info";
            Statement ps3 = (Statement) connection.createStatement();
            ResultSet rs3;
            rs3=ps3.executeQuery(sql3);
            while(rs3.next()){
                int i=rs3.getInt("max(reginum)");
                JOptionPane.showMessageDialog(null, "Please Pay Attention Your Registration Num:"+i);
            }
            dispose();
            new Patient().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
    }//GEN-LAST:event_departmentActionPerformed

    private void doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorActionPerformed
    }//GEN-LAST:event_doctorActionPerformed

    private void departmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_departmentItemStateChanged
        department.removeItem("Choose Department");
        try {
            String item = evt.getItem().toString();
            Connection connection = JDBC.getConnection();
            doctor.removeAllItems();
            String sql="select * from doctor where department=?";
            ResultSet rs;
            PreparedStatement ps = connection.prepareStatement(sql);
            ps.setString(1,item);
            rs=ps.executeQuery();
            while(rs.next()){
                doctor.addItem(rs.getString("doctor_name"));
            }
    //        if (item.equals("Surgical")) {
    //            doctor.addItem("Dr.Fu(Chief physician)");
    //            doctor.addItem("Dr.Xu(Associate chief physician)");
    //            doctor.addItem("Dr.Yue(Specialist doctors)");
    //            doctor.addItem("Dr.Chen(Specialist doctors)");
    //            doctor.addItem("Dr.Li(General physicians)");
    //            doctor.addItem("Dr.Wang(General physicians)");
    //        }
    //        if (item.equals("The Orthopaedic")) {
    //            doctor.addItem("Dr.Xu(Chief physician)");
    //            doctor.addItem("Dr.Fu(Associate chief physician)");
    //            doctor.addItem("Dr.Yue(Specialist doctors)");
    //            doctor.addItem("Dr.Chen(Specialist doctors)");
    //            doctor.addItem("Dr.Li(General physicians)");
    //            doctor.addItem("Dr.Wang(General physicians)");
    //        }
    //        if (item.equals("Pediatric")) {
    //            doctor.addItem("Dr.Yue(Chief physician)");
    //            doctor.addItem("Dr.Xu(Associate chief physician)");
    //            doctor.addItem("Dr.Fue(Specialist doctors)");
    //            doctor.addItem("Dr.Chen(Specialist doctors)");
    //            doctor.addItem("Dr.Li(General physicians)");
    //            doctor.addItem("Dr.Wang(General physicians)");
    //        }
    //        if (item.equals("Dermatology")) {
    //            doctor.addItem("Dr.Chen(Chief physician)");
    //            doctor.addItem("Dr.Fu(Associate chief physician)");
    //            doctor.addItem("Dr.Yue(Specialist doctors)");
    //            doctor.addItem("Dr.Xu(Specialist doctors)");
    //            doctor.addItem("Dr.Li(General physicians)");
    //            doctor.addItem("Dr.Wang(General physicians)");
    //        }
    //        if (item.equals("Internal medicine")) {
    //            doctor.addItem("Dr.Fu(Chief physician)");
    //            doctor.addItem("Dr.Xu(Associate chief physician)");
    //            doctor.addItem("Dr.Yue(Specialist doctors)");
    //            doctor.addItem("Dr.Chen(Specialist doctors)");
    //            doctor.addItem("Dr.Li(General physicians)");
    //            doctor.addItem("Dr.Wang(General physicians)");
    //        }
    //        if (item.equals("Ophthalmology department")) {
    //            doctor.addItem("Dr.Chen(Chief physician)");
    //            doctor.addItem("Dr.Xu(Associate chief physician)");
    //            doctor.addItem("Dr.Yue(Specialist doctors)");
    //            doctor.addItem("Dr.Fu(Specialist doctors)");
    //            doctor.addItem("Dr.Li(General physicians)");
    //        }
    //        }
        } catch (Exception ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_departmentItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Patient().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
        Registration r = new Registration();
        r.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox department;
    private javax.swing.JComboBox doctor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
