/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_Admission;
import java.awt.Color;
import java.awt.Image;
import java.awt.Point;
import java.io.File;
import java.io.FileInputStream;
import java.lang.reflect.Field;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author wolf
 */
public class Doctor_BedManagement extends javax.swing.JFrame {

    /**
     * Creates new form BedManagement
     */
    public Doctor_BedManagement() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Doctor_BedManagement");
        setLocationRelativeTo(null);
        idcard.setEnabled(false);
        bed.setEnabled(false);
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        this.setLayout(null);
        
    }
private void showInfo(String bednum)
{
    try
    {
        
        Connection con = DBClass.getConnection();
                String str = "select idcard from bed where bednumber=?";
                PreparedStatement pst=con.prepareStatement(str);
                pst.setString(1, bednum);
                ResultSet rs=pst.executeQuery();
                String id=new String();
                if(rs.next())
                {
                    id=rs.getString(1);
                }
                else
                {
                   throw new Exception("Con't find");
                }
                pst=con.prepareStatement("select * from patient where idcard=?");
                pst.setString(1, id);
                rs=pst.executeQuery();
                DefaultTableModel tm = (DefaultTableModel) info.getModel();
                tm.setRowCount(0);
                while (rs.next()) {
                   String[] a=new String[2];
//                    for (int s = 0; s < 9; s++) {
//                        if(s==2)
//                        {
//                            a = String.valueOf(rs.getInt(s+1));
//                            continue;
//                        }
//                        a = rs.getString(s + 1);
//                       tm.setValueAt(a, s+1, 2);
//                       
//                    }
//                    tm.setValueAt(bednum, 10, 2);
                a[0]="Idcard";
                a[1]=rs.getString(1);
                tm.addRow(a);
                a[0]="Name";
                a[1]=rs.getString(2);
                tm.addRow(a);
                a[0]="Age";
                a[1]=String.valueOf(rs.getInt(3));
                tm.addRow(a);
                a[0]="Sex";
                a[1]=rs.getString(4);
                tm.addRow(a);
                a[0]="DOB";
                a[1]=rs.getString(5);
                tm.addRow(a);
                a[0]="CellPhone";
                a[1]=rs.getString(6);
                tm.addRow(a);
                a[0]="Department";
                a[1]=rs.getString(7);
                tm.addRow(a);
                a[0]="DOA";
                a[1]=rs.getString(8);
                tm.addRow(a);
                a[0]="Doctor";
                a[1]=rs.getString(9);
                tm.addRow(a);
                a[0]="Bed";
                a[1]=bednum;
                tm.addRow(a);
                }
                tm.fireTableDataChanged();
                info.setVisible(true);
    }
    catch(Exception e)
    {
//        JOptionPane.showMessageDialog(this, e.getMessage());
        if(e.getMessage().equals("Con't find"))
            info.setVisible(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A1 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        E2 = new javax.swing.JLabel();
        E1 = new javax.swing.JLabel();
        E3 = new javax.swing.JLabel();
        E4 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        C2 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        patienttable = new javax.swing.JTable();
        idcard = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bedlabel = new javax.swing.JLabel();
        bed = new javax.swing.JTextField();
        arrow2 = new javax.swing.JLabel();
        arrow1 = new javax.swing.JLabel();
        arrow3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        info = new javax.swing.JTable();
        map = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                A1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                A1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                A1MouseReleased(evt);
            }
        });
        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed2.jpg"))); // NOI18N
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B1MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B1MouseReleased(evt);
            }
        });
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                A2MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                A2MouseReleased(evt);
            }
        });
        getContentPane().add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                A3MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                A3MouseReleased(evt);
            }
        });
        getContentPane().add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        A4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                A4MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                A4MouseReleased(evt);
            }
        });
        getContentPane().add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        E2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                E2MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                E2MouseReleased(evt);
            }
        });
        getContentPane().add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        E1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                E1MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                E1MouseReleased(evt);
            }
        });
        getContentPane().add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        E3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                E3MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                E3MouseReleased(evt);
            }
        });
        getContentPane().add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        E4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                E4MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                E4MousePressed(evt);
            }
        });
        getContentPane().add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed2.jpg"))); // NOI18N
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B2MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B2MouseReleased(evt);
            }
        });
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed2.jpg"))); // NOI18N
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                C1MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                C1MouseReleased(evt);
            }
        });
        getContentPane().add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed2.jpg"))); // NOI18N
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                C2MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                C2MouseReleased(evt);
            }
        });
        getContentPane().add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed2.jpg"))); // NOI18N
        D1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                D1MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                D1MouseReleased(evt);
            }
        });
        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed2.jpg"))); // NOI18N
        D2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                D2MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                D2MouseReleased(evt);
            }
        });
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        department.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SelectDepartment", "orthopedics", "pediatric", "dermatology" }));
        department.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                departmentItemStateChanged(evt);
            }
        });
        getContentPane().add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 150, -1));

        patienttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IDCard", "Name"
            }
        ));
        patienttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                patienttableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(patienttable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 240, 90));
        getContentPane().add(idcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 130, -1));

        jLabel2.setFont(new java.awt.Font("宋体", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("IDCard:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        bedlabel.setFont(new java.awt.Font("宋体", 0, 20)); // NOI18N
        bedlabel.setForeground(new java.awt.Color(255, 255, 0));
        bedlabel.setText("BedNumber:");
        getContentPane().add(bedlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, 20));

        bed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedActionPerformed(evt);
            }
        });
        getContentPane().add(bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 130, -1));

        arrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow2.jpg"))); // NOI18N
        getContentPane().add(arrow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        arrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow1.jpg"))); // NOI18N
        getContentPane().add(arrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        arrow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow3.jpg"))); // NOI18N
        getContentPane().add(arrow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Idcard", null},
                {"Name", null},
                {"Age", null},
                {"Sex", null},
                {"DOB", null},
                {"CellPhone", null},
                {"Department", null},
                {"DOA", null},
                {"Doctor", null},
                {"Bed", null}
            },
            new String [] {
                "Property", "Info"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(info);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 160, 190));

        map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/map.png"))); // NOI18N
        getContentPane().add(map, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel3.setText("Tips 1.Select a department.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel4.setText("2.Then you will get some rows in the table select one of them.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel5.setText("3.Enter your mouse into the bed icon and you can find private infomation →");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jButton1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/desk1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void departmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_departmentItemStateChanged
        patienttable.removeAll();
        String item = evt.getItem().toString();
        try {
            if (item.equals("orthopedics")) {
                patienttable.removeAll();
                Connection con = DBClass.getConnection();
                String str = "select * from patient where department='orthopedics'";
                Statement st = (Statement) con.createStatement();
                ResultSet rs = st.executeQuery(str);
                DefaultTableModel tm = (DefaultTableModel) patienttable.getModel();
                tm.setRowCount(0);
                while (rs.next()) {
                    String[] a = new String[2];
                    for (int s = 0; s < 2; s++) {
                        a[s] = rs.getString(s + 1);
                    }
                    tm.addRow(a);
                }
                tm.fireTableDataChanged();
            } else if (item.equals("pediatric")) {
                patienttable.removeAll();
                Connection con = DBClass.getConnection();
                String str = "select * from patient where department='pediatric'";
                Statement st = (Statement) con.createStatement();
                ResultSet rs = st.executeQuery(str);
                DefaultTableModel tm = (DefaultTableModel) patienttable.getModel();
                tm.setRowCount(0);
                while (rs.next()) {
                    String[] a = new String[2];
                    for (int s = 0; s < 2; s++) {
                        a[s] = rs.getString(s + 1);
                    }
                    tm.addRow(a);
                }
                tm.fireTableDataChanged();
            } else if (item.equals("dermatology")) {
                patienttable.removeAll();
                Connection con = DBClass.getConnection();

                String str = "select * from patient where department='dermatology'";
                Statement st = (Statement) con.createStatement();
                ResultSet rs = st.executeQuery(str);
                DefaultTableModel tm = (DefaultTableModel) patienttable.getModel();
                tm.setRowCount(0);
                while (rs.next()) {
                    String[] a = new String[2];
                    for (int s = 0; s < 2; s++) {
                        a[s] = rs.getString(s + 1);
                    }
                    tm.addRow(a);
                }
                tm.fireTableDataChanged();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_departmentItemStateChanged

    private void patienttableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patienttableMouseReleased
        String[][] NameToLocation={{"A1",String.valueOf(A1.getLocation().x),String.valueOf(A1.getLocation().y)},
        {"A2",String.valueOf(A2.getLocation().x),String.valueOf(A2.getLocation().y)},
        {"A3",String.valueOf(A3.getLocation().x),String.valueOf(A3.getLocation().y)},
        {"A4",String.valueOf(A4.getLocation().x),String.valueOf(A4.getLocation().y)},
        {"B1",String.valueOf(B1.getLocation().x),String.valueOf(B1.getLocation().y)},
        {"B2",String.valueOf(B2.getLocation().x),String.valueOf(B2.getLocation().y)},
        {"C1",String.valueOf(C1.getLocation().x),String.valueOf(C1.getLocation().y)},
        {"C2",String.valueOf(C2.getLocation().x),String.valueOf(C2.getLocation().y)},
        {"D1",String.valueOf(D1.getLocation().x),String.valueOf(D1.getLocation().y)},
        {"D2",String.valueOf(D2.getLocation().x),String.valueOf(D2.getLocation().y)},
        {"E1",String.valueOf(E1.getLocation().x),String.valueOf(E1.getLocation().y)},
        {"E2",String.valueOf(E2.getLocation().x),String.valueOf(E2.getLocation().y)},
        {"E3",String.valueOf(E3.getLocation().x),String.valueOf(E3.getLocation().y)},
        {"E4",String.valueOf(E4.getLocation().x),String.valueOf(E4.getLocation().y)}};
        
        if (patienttable.getSelectedRowCount() > 0) {
            bed.setText(null);
            int rownum = patienttable.getSelectedRow();
            String id = patienttable.getValueAt(rownum, 0).toString();
            idcard.setText(id);
            try
            {
                Connection con=DBClass.getConnection();
                PreparedStatement pst=con.prepareStatement("select bednumber from bed where idcard=?");
                pst.setString(1, id);
                ResultSet rs=pst.executeQuery();
                if(rs.next())
                {
                    bed.setText(rs.getString(1));
                    int i=0;
                    while(!bed.getText().equals(NameToLocation[i][0]))
                    {
                        ++i;
                    }                    
                    if(i<4)
                    {
                        arrow1.setVisible(false);
                    arrow2.setVisible(false);
                    arrow3.setVisible(false);
                    arrow1.setVisible(true);
                    Point p=new Point(Integer.parseInt(NameToLocation[i][1]),Integer.parseInt(NameToLocation[i][2]));
                    p.x-=35;
                    arrow1.setLocation(p);
                    }
                    else if(i<10)
                    {
                        arrow1.setVisible(false);
                arrow2.setVisible(false);
                arrow3.setVisible(false);
                arrow2.setVisible(true);
                Point p=new Point(Integer.parseInt(NameToLocation[i][1]),Integer.parseInt(NameToLocation[i][2]));
                p.y+=35;
                p.x+=5;
                arrow2.setLocation(p);
       
                    }
                    else
                    {
                        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow3.setVisible(true);
        Point p=new Point(Integer.parseInt(NameToLocation[i][1]),Integer.parseInt(NameToLocation[i][2]));
        p.x+=35;
        arrow3.setLocation(p);
                    }
//                    

                }
                else
                {
                    JOptionPane.showMessageDialog(this, "He/She doesn't have a bed.");
                }
            }
            catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }

        }
    }//GEN-LAST:event_patienttableMouseReleased

    private void A1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow1.setVisible(true);
        Point p=new Point(A1.getLocation());
        p.x-=35;
       arrow1.setLocation(p);
        bed.setText("A1");
        
    }//GEN-LAST:event_A1MouseReleased

    private void A2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow1.setVisible(true);
        Point p=new Point(A2.getLocation());
        p.x-=35;
       arrow1.setLocation(p);
        bed.setText("A2");
    }//GEN-LAST:event_A2MouseReleased

    private void A3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow1.setVisible(true);
        Point p=new Point(A3.getLocation());
        p.x-=35;
       arrow1.setLocation(p);
        bed.setText("A3");
    }//GEN-LAST:event_A3MouseReleased

    private void A4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A4MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow1.setVisible(true);
        Point p=new Point(A4.getLocation());
        p.x-=35;
       arrow1.setLocation(p);
        bed.setText("A4");
    }//GEN-LAST:event_A4MouseReleased

    private void E1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E1MouseReleased
       
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow3.setVisible(true);
        Point p=new Point(E1.getLocation());
        p.x+=35;
        arrow3.setLocation(p);
        bed.setText("E1");
    }//GEN-LAST:event_E1MouseReleased

    private void E2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow3.setVisible(true);
        Point p=new Point(E2.getLocation());
        p.x+=35;
        arrow3.setLocation(p);
        bed.setText("E2");
    }//GEN-LAST:event_E2MouseReleased

    private void E3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E3MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow3.setVisible(true);
        Point p=new Point(E3.getLocation());
        p.x+=35;
        arrow3.setLocation(p);
        bed.setText("E3");
    }//GEN-LAST:event_E3MouseReleased

    private void E4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E4MousePressed
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow3.setVisible(true);
        Point p=new Point(E4.getLocation());
        p.x+=35;
        arrow3.setLocation(p);
        bed.setText("E4");
    }//GEN-LAST:event_E4MousePressed

    private void B1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow2.setVisible(true);
        Point p=new Point(B1.getLocation());
        p.y+=35;
        p.x+=5;
        arrow2.setLocation(p);
        bed.setText("B1");
    }//GEN-LAST:event_B1MouseReleased

    private void B2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow2.setVisible(true);
        Point p=new Point(B2.getLocation());
        p.y+=35;
        p.x+=5;
        arrow2.setLocation(p);
        bed.setText("B2");
    }//GEN-LAST:event_B2MouseReleased

    private void C1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow2.setVisible(true);
        Point p=new Point(C1.getLocation());
        p.y+=35;
        p.x+=5;
        arrow2.setLocation(p);
        bed.setText("C1");
    }//GEN-LAST:event_C1MouseReleased

    private void C2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow2.setVisible(true);
        Point p=new Point(C2.getLocation());
        p.y+=35;
        p.x+=5;
        arrow2.setLocation(p);
        bed.setText("C2");
    }//GEN-LAST:event_C2MouseReleased

    private void D1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D1MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow2.setVisible(true);
        Point p=new Point(D1.getLocation());
        p.y+=35;
        p.x+=5;
        arrow2.setLocation(p);
        bed.setText("D1");
    }//GEN-LAST:event_D1MouseReleased

    private void D2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D2MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow2.setVisible(true);
        Point p=new Point(D2.getLocation());
        p.y+=35;
        p.x+=5;
        arrow2.setLocation(p);
        bed.setText("D2");
    }//GEN-LAST:event_D2MouseReleased

    private void A1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseEntered
        showInfo("A1");
        
      
    }//GEN-LAST:event_A1MouseEntered

    private void A1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseExited
       
    }//GEN-LAST:event_A1MouseExited

    private void A2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseEntered
showInfo("A2");        // TODO add your handling code here:
    }//GEN-LAST:event_A2MouseEntered

    private void A3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseEntered
showInfo("A3");        // TODO add your handling code here:
    }//GEN-LAST:event_A3MouseEntered

    private void A4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A4MouseEntered
showInfo("A4");        // TODO add your handling code here:
    }//GEN-LAST:event_A4MouseEntered

    private void B1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseEntered
 showInfo("B1");       // TODO add your handling code here:
    }//GEN-LAST:event_B1MouseEntered

    private void B2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseEntered
 showInfo("B2");       // TODO add your handling code here:
    }//GEN-LAST:event_B2MouseEntered

    private void C1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseEntered
   showInfo("C1");     // TODO add your handling code here:
    }//GEN-LAST:event_C1MouseEntered

    private void C2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseEntered
 showInfo("C2");       // TODO add your handling code here:
    }//GEN-LAST:event_C2MouseEntered

    private void D1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D1MouseEntered
  showInfo("D1");      // TODO add your handling code here:
    }//GEN-LAST:event_D1MouseEntered

    private void D2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D2MouseEntered
  showInfo("D2");      // TODO add your handling code here:
    }//GEN-LAST:event_D2MouseEntered

    private void E1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E1MouseEntered
   showInfo("E1");     // TODO add your handling code here:
    }//GEN-LAST:event_E1MouseEntered

    private void E2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2MouseEntered
   showInfo("E2");     // TODO add your handling code here:
    }//GEN-LAST:event_E2MouseEntered

    private void E3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E3MouseEntered
  showInfo("E3");      // TODO add your handling code here:
    }//GEN-LAST:event_E3MouseEntered

    private void E4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E4MouseEntered
  showInfo("E4");      // TODO add your handling code here:
    }//GEN-LAST:event_E4MouseEntered

    private void bedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
        new Hospital_Management().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_BedManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_BedManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_BedManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_BedManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Doctor_BedManagement().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel C2;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel E1;
    private javax.swing.JLabel E2;
    private javax.swing.JLabel E3;
    private javax.swing.JLabel E4;
    private javax.swing.JLabel arrow1;
    private javax.swing.JLabel arrow2;
    private javax.swing.JLabel arrow3;
    private javax.swing.JTextField bed;
    private javax.swing.JLabel bedlabel;
    private javax.swing.JComboBox department;
    private javax.swing.JTextField idcard;
    private javax.swing.JTable info;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel map;
    private javax.swing.JTable patienttable;
    // End of variables declaration//GEN-END:variables
}
