/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_Admission;
import java.awt.Color;
import java.awt.Image;
import java.awt.Point;
import java.io.File;
import java.io.FileInputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author wolf
 */
public class Patient_BedManagement extends javax.swing.JFrame {

    /**
     * Creates new form BedManagement
     */
    public Patient_BedManagement() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Patient_BedManagement");
        setLocationRelativeTo(null);
        idcard.setEnabled(false);
        bed.setEnabled(false);
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        this.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A1 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        E2 = new javax.swing.JLabel();
        E1 = new javax.swing.JLabel();
        E3 = new javax.swing.JLabel();
        E4 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        C2 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        patienttable = new javax.swing.JTable();
        idcard = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bedlabel = new javax.swing.JLabel();
        bed = new javax.swing.JTextField();
        arrow2 = new javax.swing.JLabel();
        arrow1 = new javax.swing.JLabel();
        arrow3 = new javax.swing.JLabel();
        map = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                A1MouseReleased(evt);
            }
        });
        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed2.jpg"))); // NOI18N
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B1MouseReleased(evt);
            }
        });
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                A2MouseReleased(evt);
            }
        });
        getContentPane().add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, -1, -1));

        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                A3MouseReleased(evt);
            }
        });
        getContentPane().add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, -1, -1));

        A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        A4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                A4MouseReleased(evt);
            }
        });
        getContentPane().add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, -1, -1));

        E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        E2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                E2MouseReleased(evt);
            }
        });
        getContentPane().add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        E1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                E1MouseReleased(evt);
            }
        });
        getContentPane().add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        E3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                E3MouseReleased(evt);
            }
        });
        getContentPane().add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed1.jpg"))); // NOI18N
        E4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                E4MousePressed(evt);
            }
        });
        getContentPane().add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed2.jpg"))); // NOI18N
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                B2MouseReleased(evt);
            }
        });
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed2.jpg"))); // NOI18N
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                C1MouseReleased(evt);
            }
        });
        getContentPane().add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed2.jpg"))); // NOI18N
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                C2MouseReleased(evt);
            }
        });
        getContentPane().add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed2.jpg"))); // NOI18N
        D1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                D1MouseReleased(evt);
            }
        });
        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bed2.jpg"))); // NOI18N
        D2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                D2MouseReleased(evt);
            }
        });
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        department.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        department.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SelectDepartment", "orthopedics", "pediatric", "dermatology" }));
        department.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                departmentItemStateChanged(evt);
            }
        });
        getContentPane().add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        patienttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IDCard", "Name"
            }
        ));
        patienttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                patienttableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(patienttable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 240, 90));
        getContentPane().add(idcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 130, -1));

        jLabel2.setFont(new java.awt.Font("宋体", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("IDCard");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        bedlabel.setFont(new java.awt.Font("宋体", 0, 20)); // NOI18N
        bedlabel.setForeground(new java.awt.Color(255, 255, 0));
        bedlabel.setText("BedNumber");
        getContentPane().add(bedlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 20));
        getContentPane().add(bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 130, -1));

        arrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow2.jpg"))); // NOI18N
        getContentPane().add(arrow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        arrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow1.jpg"))); // NOI18N
        getContentPane().add(arrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, -1));

        arrow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow3.jpg"))); // NOI18N
        getContentPane().add(arrow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, -1));

        map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/map.png"))); // NOI18N
        getContentPane().add(map, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        submit.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel3.setText("Tips 1.Select a department.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel4.setText("2.Then you will get some rows and select one of them.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel5.setText("3.Click a bed icon from right side and you will get bed number.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel6.setText("4.Click submit buttuon to deliver the data.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jButton1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/desk4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void departmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_departmentItemStateChanged
        patienttable.removeAll();
        String item = evt.getItem().toString();
        try {
            if (item.equals("orthopedics")) {
                patienttable.removeAll();
                Connection con = DBClass.getConnection();
                String str = "select * from patient where department='orthopedics'";
                Statement st = (Statement) con.createStatement();
                ResultSet rs = st.executeQuery(str);
                DefaultTableModel tm = (DefaultTableModel) patienttable.getModel();
                tm.setRowCount(0);
                while (rs.next()) {
                    String[] a = new String[2];
                    for (int s = 0; s < 2; s++) {
                        a[s] = rs.getString(s + 1);
                    }
                    tm.addRow(a);
                }
                tm.fireTableDataChanged();
            } else if (item.equals("pediatric")) {
                patienttable.removeAll();
                Connection con = DBClass.getConnection();
                String str = "select * from patient where department='pediatric'";
                Statement st = (Statement) con.createStatement();
                ResultSet rs = st.executeQuery(str);
                DefaultTableModel tm = (DefaultTableModel) patienttable.getModel();
                tm.setRowCount(0);
                while (rs.next()) {
                    String[] a = new String[2];
                    for (int s = 0; s < 2; s++) {
                        a[s] = rs.getString(s + 1);
                    }
                    tm.addRow(a);
                }
                tm.fireTableDataChanged();
            } else if (item.equals("dermatology")) {
                patienttable.removeAll();
                Connection con = DBClass.getConnection();

                String str = "select * from patient where department='dermatology'";
                Statement st = (Statement) con.createStatement();
                ResultSet rs = st.executeQuery(str);
                DefaultTableModel tm = (DefaultTableModel) patienttable.getModel();
                tm.setRowCount(0);
                while (rs.next()) {
                    String[] a = new String[2];
                    for (int s = 0; s < 2; s++) {
                        a[s] = rs.getString(s + 1);
                    }
                    tm.addRow(a);
                }
                tm.fireTableDataChanged();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_departmentItemStateChanged

    private void patienttableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patienttableMouseReleased
        if (patienttable.getSelectedRowCount() > 0) {
            int rownum = patienttable.getSelectedRow();
            String id = patienttable.getValueAt(rownum, 0).toString();
            idcard.setText(id);

        }
    }//GEN-LAST:event_patienttableMouseReleased

    private void A1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow1.setVisible(true);
        Point p=new Point(A1.getLocation());
        p.x-=35;
       arrow1.setLocation(p);
        bed.setText("A1");
        
    }//GEN-LAST:event_A1MouseReleased

    private void A2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow1.setVisible(true);
        Point p=new Point(A2.getLocation());
        p.x-=35;
       arrow1.setLocation(p);
        bed.setText("A2");
    }//GEN-LAST:event_A2MouseReleased

    private void A3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow1.setVisible(true);
        Point p=new Point(A3.getLocation());
        p.x-=35;
       arrow1.setLocation(p);
        bed.setText("A3");
    }//GEN-LAST:event_A3MouseReleased

    private void A4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A4MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow1.setVisible(true);
        Point p=new Point(A4.getLocation());
        p.x-=35;
       arrow1.setLocation(p);
        bed.setText("A4");
    }//GEN-LAST:event_A4MouseReleased

    private void E1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E1MouseReleased
       
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow3.setVisible(true);
        Point p=new Point(E1.getLocation());
        p.x+=35;
        arrow3.setLocation(p);
        bed.setText("E1");
    }//GEN-LAST:event_E1MouseReleased

    private void E2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow3.setVisible(true);
        Point p=new Point(E2.getLocation());
        p.x+=35;
        arrow3.setLocation(p);
        bed.setText("E2");
    }//GEN-LAST:event_E2MouseReleased

    private void E3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E3MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow3.setVisible(true);
        Point p=new Point(E3.getLocation());
        p.x+=35;
        arrow3.setLocation(p);
        bed.setText("E3");
    }//GEN-LAST:event_E3MouseReleased

    private void E4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E4MousePressed
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow3.setVisible(true);
        Point p=new Point(E4.getLocation());
        p.x+=35;
        arrow3.setLocation(p);
        bed.setText("E4");
    }//GEN-LAST:event_E4MousePressed

    private void B1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow2.setVisible(true);
        Point p=new Point(B1.getLocation());
        p.y+=35;
        p.x+=5;
        arrow2.setLocation(p);
        bed.setText("B1");
    }//GEN-LAST:event_B1MouseReleased

    private void B2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow2.setVisible(true);
        Point p=new Point(B2.getLocation());
        p.y+=35;
        p.x+=5;
        arrow2.setLocation(p);
        bed.setText("B2");
    }//GEN-LAST:event_B2MouseReleased

    private void C1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow2.setVisible(true);
        Point p=new Point(C1.getLocation());
        p.y+=35;
        p.x+=5;
        arrow2.setLocation(p);
        bed.setText("C1");
    }//GEN-LAST:event_C1MouseReleased

    private void C2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow2.setVisible(true);
        Point p=new Point(C2.getLocation());
        p.y+=35;
        p.x+=5;
        arrow2.setLocation(p);
        bed.setText("C2");
    }//GEN-LAST:event_C2MouseReleased

    private void D1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D1MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow2.setVisible(true);
        Point p=new Point(D1.getLocation());
        p.y+=35;
        p.x+=5;
        arrow2.setLocation(p);
        bed.setText("D1");
    }//GEN-LAST:event_D1MouseReleased

    private void D2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D2MouseReleased
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow2.setVisible(true);
        Point p=new Point(D2.getLocation());
        p.y+=35;
        p.x+=5;
        arrow2.setLocation(p);
        bed.setText("D2");
    }//GEN-LAST:event_D2MouseReleased

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
             Connection con = DBClass.getConnection();
 
            PreparedStatement st = con.prepareStatement("insert into bed values(?,?)");
            st.setString(1, idcard.getText());


           st.setString(2, bed.getText());
            int count = st.executeUpdate();
            if (count > 0) {
                JOptionPane.showMessageDialog(this, "Data Saved Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Error Saving Data");
            }
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(this,ex.getMessage().toString());
            System.out.println(ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
new Hospital_Management().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient_BedManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient_BedManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient_BedManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient_BedManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Patient_BedManagement().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel C2;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel E1;
    private javax.swing.JLabel E2;
    private javax.swing.JLabel E3;
    private javax.swing.JLabel E4;
    private javax.swing.JLabel arrow1;
    private javax.swing.JLabel arrow2;
    private javax.swing.JLabel arrow3;
    private javax.swing.JTextField bed;
    private javax.swing.JLabel bedlabel;
    private javax.swing.JComboBox department;
    private javax.swing.JTextField idcard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel map;
    private javax.swing.JTable patienttable;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
